/* soapH.h
   Generated by gSOAP 2.7.14 from josso-1.2.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__SSONameValuePairType
#define SOAP_TYPE_ns3__SSONameValuePairType (36)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SSONameValuePairType(struct soap*, const char*, int, const ns3__SSONameValuePairType *, const char*);
SOAP_FMAC3 ns3__SSONameValuePairType * SOAP_FMAC4 soap_get_ns3__SSONameValuePairType(struct soap*, ns3__SSONameValuePairType *, const char*, const char*);
SOAP_FMAC3 ns3__SSONameValuePairType * SOAP_FMAC4 soap_in_ns3__SSONameValuePairType(struct soap*, const char*, ns3__SSONameValuePairType *, const char*);

#define soap_new_ns3__SSONameValuePairType(soap, n) soap_instantiate_ns3__SSONameValuePairType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__SSONameValuePairType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__SSONameValuePairType * SOAP_FMAC4 soap_instantiate_ns3__SSONameValuePairType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__SSONameValuePairType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__SSORoleType
#define SOAP_TYPE_ns3__SSORoleType (35)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SSORoleType(struct soap*, const char*, int, const ns3__SSORoleType *, const char*);
SOAP_FMAC3 ns3__SSORoleType * SOAP_FMAC4 soap_get_ns3__SSORoleType(struct soap*, ns3__SSORoleType *, const char*, const char*);
SOAP_FMAC3 ns3__SSORoleType * SOAP_FMAC4 soap_in_ns3__SSORoleType(struct soap*, const char*, ns3__SSORoleType *, const char*);

#define soap_new_ns3__SSORoleType(soap, n) soap_instantiate_ns3__SSORoleType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__SSORoleType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__SSORoleType * SOAP_FMAC4 soap_instantiate_ns3__SSORoleType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__SSORoleType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__SSOUserType
#define SOAP_TYPE_ns3__SSOUserType (34)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SSOUserType(struct soap*, const char*, int, const ns3__SSOUserType *, const char*);
SOAP_FMAC3 ns3__SSOUserType * SOAP_FMAC4 soap_get_ns3__SSOUserType(struct soap*, ns3__SSOUserType *, const char*, const char*);
SOAP_FMAC3 ns3__SSOUserType * SOAP_FMAC4 soap_in_ns3__SSOUserType(struct soap*, const char*, ns3__SSOUserType *, const char*);

#define soap_new_ns3__SSOUserType(soap, n) soap_instantiate_ns3__SSOUserType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__SSOUserType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__SSOUserType * SOAP_FMAC4 soap_instantiate_ns3__SSOUserType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__SSOUserType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__SSOSessionType
#define SOAP_TYPE_ns3__SSOSessionType (33)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SSOSessionType(struct soap*, const char*, int, const ns3__SSOSessionType *, const char*);
SOAP_FMAC3 ns3__SSOSessionType * SOAP_FMAC4 soap_get_ns3__SSOSessionType(struct soap*, ns3__SSOSessionType *, const char*, const char*);
SOAP_FMAC3 ns3__SSOSessionType * SOAP_FMAC4 soap_in_ns3__SSOSessionType(struct soap*, const char*, ns3__SSOSessionType *, const char*);

#define soap_new_ns3__SSOSessionType(soap, n) soap_instantiate_ns3__SSOSessionType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__SSOSessionType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__SSOSessionType * SOAP_FMAC4 soap_instantiate_ns3__SSOSessionType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__SSOSessionType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__NoSuchSessionErrorType
#define SOAP_TYPE_ns3__NoSuchSessionErrorType (32)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__NoSuchSessionErrorType(struct soap*, const char*, int, const ns3__NoSuchSessionErrorType *, const char*);
SOAP_FMAC3 ns3__NoSuchSessionErrorType * SOAP_FMAC4 soap_get_ns3__NoSuchSessionErrorType(struct soap*, ns3__NoSuchSessionErrorType *, const char*, const char*);
SOAP_FMAC3 ns3__NoSuchSessionErrorType * SOAP_FMAC4 soap_in_ns3__NoSuchSessionErrorType(struct soap*, const char*, ns3__NoSuchSessionErrorType *, const char*);

#define soap_new_ns3__NoSuchSessionErrorType(soap, n) soap_instantiate_ns3__NoSuchSessionErrorType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__NoSuchSessionErrorType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__NoSuchSessionErrorType * SOAP_FMAC4 soap_instantiate_ns3__NoSuchSessionErrorType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__NoSuchSessionErrorType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__SSOSessionErrorType
#define SOAP_TYPE_ns3__SSOSessionErrorType (31)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SSOSessionErrorType(struct soap*, const char*, int, const ns3__SSOSessionErrorType *, const char*);
SOAP_FMAC3 ns3__SSOSessionErrorType * SOAP_FMAC4 soap_get_ns3__SSOSessionErrorType(struct soap*, ns3__SSOSessionErrorType *, const char*, const char*);
SOAP_FMAC3 ns3__SSOSessionErrorType * SOAP_FMAC4 soap_in_ns3__SSOSessionErrorType(struct soap*, const char*, ns3__SSOSessionErrorType *, const char*);

#define soap_new_ns3__SSOSessionErrorType(soap, n) soap_instantiate_ns3__SSOSessionErrorType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__SSOSessionErrorType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__SSOSessionErrorType * SOAP_FMAC4 soap_instantiate_ns3__SSOSessionErrorType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__SSOSessionErrorType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__SessionResponseType
#define SOAP_TYPE_ns3__SessionResponseType (30)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SessionResponseType(struct soap*, const char*, int, const ns3__SessionResponseType *, const char*);
SOAP_FMAC3 ns3__SessionResponseType * SOAP_FMAC4 soap_get_ns3__SessionResponseType(struct soap*, ns3__SessionResponseType *, const char*, const char*);
SOAP_FMAC3 ns3__SessionResponseType * SOAP_FMAC4 soap_in_ns3__SessionResponseType(struct soap*, const char*, ns3__SessionResponseType *, const char*);

#define soap_new_ns3__SessionResponseType(soap, n) soap_instantiate_ns3__SessionResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__SessionResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__SessionResponseType * SOAP_FMAC4 soap_instantiate_ns3__SessionResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__SessionResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__SessionRequestType
#define SOAP_TYPE_ns3__SessionRequestType (29)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SessionRequestType(struct soap*, const char*, int, const ns3__SessionRequestType *, const char*);
SOAP_FMAC3 ns3__SessionRequestType * SOAP_FMAC4 soap_get_ns3__SessionRequestType(struct soap*, ns3__SessionRequestType *, const char*, const char*);
SOAP_FMAC3 ns3__SessionRequestType * SOAP_FMAC4 soap_in_ns3__SessionRequestType(struct soap*, const char*, ns3__SessionRequestType *, const char*);

#define soap_new_ns3__SessionRequestType(soap, n) soap_instantiate_ns3__SessionRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__SessionRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__SessionRequestType * SOAP_FMAC4 soap_instantiate_ns3__SessionRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__SessionRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__AccessSessionResponseType
#define SOAP_TYPE_ns3__AccessSessionResponseType (28)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__AccessSessionResponseType(struct soap*, const char*, int, const ns3__AccessSessionResponseType *, const char*);
SOAP_FMAC3 ns3__AccessSessionResponseType * SOAP_FMAC4 soap_get_ns3__AccessSessionResponseType(struct soap*, ns3__AccessSessionResponseType *, const char*, const char*);
SOAP_FMAC3 ns3__AccessSessionResponseType * SOAP_FMAC4 soap_in_ns3__AccessSessionResponseType(struct soap*, const char*, ns3__AccessSessionResponseType *, const char*);

#define soap_new_ns3__AccessSessionResponseType(soap, n) soap_instantiate_ns3__AccessSessionResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__AccessSessionResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__AccessSessionResponseType * SOAP_FMAC4 soap_instantiate_ns3__AccessSessionResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__AccessSessionResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__AccessSessionRequestType
#define SOAP_TYPE_ns3__AccessSessionRequestType (27)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__AccessSessionRequestType(struct soap*, const char*, int, const ns3__AccessSessionRequestType *, const char*);
SOAP_FMAC3 ns3__AccessSessionRequestType * SOAP_FMAC4 soap_get_ns3__AccessSessionRequestType(struct soap*, ns3__AccessSessionRequestType *, const char*, const char*);
SOAP_FMAC3 ns3__AccessSessionRequestType * SOAP_FMAC4 soap_in_ns3__AccessSessionRequestType(struct soap*, const char*, ns3__AccessSessionRequestType *, const char*);

#define soap_new_ns3__AccessSessionRequestType(soap, n) soap_instantiate_ns3__AccessSessionRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__AccessSessionRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__AccessSessionRequestType * SOAP_FMAC4 soap_instantiate_ns3__AccessSessionRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__AccessSessionRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__InvalidSessionErrorType
#define SOAP_TYPE_ns3__InvalidSessionErrorType (26)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__InvalidSessionErrorType(struct soap*, const char*, int, const ns3__InvalidSessionErrorType *, const char*);
SOAP_FMAC3 ns3__InvalidSessionErrorType * SOAP_FMAC4 soap_get_ns3__InvalidSessionErrorType(struct soap*, ns3__InvalidSessionErrorType *, const char*, const char*);
SOAP_FMAC3 ns3__InvalidSessionErrorType * SOAP_FMAC4 soap_in_ns3__InvalidSessionErrorType(struct soap*, const char*, ns3__InvalidSessionErrorType *, const char*);

#define soap_new_ns3__InvalidSessionErrorType(soap, n) soap_instantiate_ns3__InvalidSessionErrorType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__InvalidSessionErrorType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__InvalidSessionErrorType * SOAP_FMAC4 soap_instantiate_ns3__InvalidSessionErrorType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__InvalidSessionErrorType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__NoSuchUserErrorType
#define SOAP_TYPE_ns3__NoSuchUserErrorType (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__NoSuchUserErrorType(struct soap*, const char*, int, const ns3__NoSuchUserErrorType *, const char*);
SOAP_FMAC3 ns3__NoSuchUserErrorType * SOAP_FMAC4 soap_get_ns3__NoSuchUserErrorType(struct soap*, ns3__NoSuchUserErrorType *, const char*, const char*);
SOAP_FMAC3 ns3__NoSuchUserErrorType * SOAP_FMAC4 soap_in_ns3__NoSuchUserErrorType(struct soap*, const char*, ns3__NoSuchUserErrorType *, const char*);

#define soap_new_ns3__NoSuchUserErrorType(soap, n) soap_instantiate_ns3__NoSuchUserErrorType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__NoSuchUserErrorType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__NoSuchUserErrorType * SOAP_FMAC4 soap_instantiate_ns3__NoSuchUserErrorType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__NoSuchUserErrorType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__SSOIdentityManagerErrorType
#define SOAP_TYPE_ns3__SSOIdentityManagerErrorType (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SSOIdentityManagerErrorType(struct soap*, const char*, int, const ns3__SSOIdentityManagerErrorType *, const char*);
SOAP_FMAC3 ns3__SSOIdentityManagerErrorType * SOAP_FMAC4 soap_get_ns3__SSOIdentityManagerErrorType(struct soap*, ns3__SSOIdentityManagerErrorType *, const char*, const char*);
SOAP_FMAC3 ns3__SSOIdentityManagerErrorType * SOAP_FMAC4 soap_in_ns3__SSOIdentityManagerErrorType(struct soap*, const char*, ns3__SSOIdentityManagerErrorType *, const char*);

#define soap_new_ns3__SSOIdentityManagerErrorType(soap, n) soap_instantiate_ns3__SSOIdentityManagerErrorType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__SSOIdentityManagerErrorType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__SSOIdentityManagerErrorType * SOAP_FMAC4 soap_instantiate_ns3__SSOIdentityManagerErrorType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__SSOIdentityManagerErrorType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__UserExistsResponseType
#define SOAP_TYPE_ns3__UserExistsResponseType (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__UserExistsResponseType(struct soap*, const char*, int, const ns3__UserExistsResponseType *, const char*);
SOAP_FMAC3 ns3__UserExistsResponseType * SOAP_FMAC4 soap_get_ns3__UserExistsResponseType(struct soap*, ns3__UserExistsResponseType *, const char*, const char*);
SOAP_FMAC3 ns3__UserExistsResponseType * SOAP_FMAC4 soap_in_ns3__UserExistsResponseType(struct soap*, const char*, ns3__UserExistsResponseType *, const char*);

#define soap_new_ns3__UserExistsResponseType(soap, n) soap_instantiate_ns3__UserExistsResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__UserExistsResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__UserExistsResponseType * SOAP_FMAC4 soap_instantiate_ns3__UserExistsResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__UserExistsResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__UserExistsRequestType
#define SOAP_TYPE_ns3__UserExistsRequestType (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__UserExistsRequestType(struct soap*, const char*, int, const ns3__UserExistsRequestType *, const char*);
SOAP_FMAC3 ns3__UserExistsRequestType * SOAP_FMAC4 soap_get_ns3__UserExistsRequestType(struct soap*, ns3__UserExistsRequestType *, const char*, const char*);
SOAP_FMAC3 ns3__UserExistsRequestType * SOAP_FMAC4 soap_in_ns3__UserExistsRequestType(struct soap*, const char*, ns3__UserExistsRequestType *, const char*);

#define soap_new_ns3__UserExistsRequestType(soap, n) soap_instantiate_ns3__UserExistsRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__UserExistsRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__UserExistsRequestType * SOAP_FMAC4 soap_instantiate_ns3__UserExistsRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__UserExistsRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__FindRolesBySSOSessionIdResponseType
#define SOAP_TYPE_ns3__FindRolesBySSOSessionIdResponseType (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__FindRolesBySSOSessionIdResponseType(struct soap*, const char*, int, const ns3__FindRolesBySSOSessionIdResponseType *, const char*);
SOAP_FMAC3 ns3__FindRolesBySSOSessionIdResponseType * SOAP_FMAC4 soap_get_ns3__FindRolesBySSOSessionIdResponseType(struct soap*, ns3__FindRolesBySSOSessionIdResponseType *, const char*, const char*);
SOAP_FMAC3 ns3__FindRolesBySSOSessionIdResponseType * SOAP_FMAC4 soap_in_ns3__FindRolesBySSOSessionIdResponseType(struct soap*, const char*, ns3__FindRolesBySSOSessionIdResponseType *, const char*);

#define soap_new_ns3__FindRolesBySSOSessionIdResponseType(soap, n) soap_instantiate_ns3__FindRolesBySSOSessionIdResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__FindRolesBySSOSessionIdResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__FindRolesBySSOSessionIdResponseType * SOAP_FMAC4 soap_instantiate_ns3__FindRolesBySSOSessionIdResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__FindRolesBySSOSessionIdResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__FindRolesBySSOSessionIdRequestType
#define SOAP_TYPE_ns3__FindRolesBySSOSessionIdRequestType (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__FindRolesBySSOSessionIdRequestType(struct soap*, const char*, int, const ns3__FindRolesBySSOSessionIdRequestType *, const char*);
SOAP_FMAC3 ns3__FindRolesBySSOSessionIdRequestType * SOAP_FMAC4 soap_get_ns3__FindRolesBySSOSessionIdRequestType(struct soap*, ns3__FindRolesBySSOSessionIdRequestType *, const char*, const char*);
SOAP_FMAC3 ns3__FindRolesBySSOSessionIdRequestType * SOAP_FMAC4 soap_in_ns3__FindRolesBySSOSessionIdRequestType(struct soap*, const char*, ns3__FindRolesBySSOSessionIdRequestType *, const char*);

#define soap_new_ns3__FindRolesBySSOSessionIdRequestType(soap, n) soap_instantiate_ns3__FindRolesBySSOSessionIdRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__FindRolesBySSOSessionIdRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__FindRolesBySSOSessionIdRequestType * SOAP_FMAC4 soap_instantiate_ns3__FindRolesBySSOSessionIdRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__FindRolesBySSOSessionIdRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__FindUserInSecurityDomainResponseType
#define SOAP_TYPE_ns3__FindUserInSecurityDomainResponseType (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__FindUserInSecurityDomainResponseType(struct soap*, const char*, int, const ns3__FindUserInSecurityDomainResponseType *, const char*);
SOAP_FMAC3 ns3__FindUserInSecurityDomainResponseType * SOAP_FMAC4 soap_get_ns3__FindUserInSecurityDomainResponseType(struct soap*, ns3__FindUserInSecurityDomainResponseType *, const char*, const char*);
SOAP_FMAC3 ns3__FindUserInSecurityDomainResponseType * SOAP_FMAC4 soap_in_ns3__FindUserInSecurityDomainResponseType(struct soap*, const char*, ns3__FindUserInSecurityDomainResponseType *, const char*);

#define soap_new_ns3__FindUserInSecurityDomainResponseType(soap, n) soap_instantiate_ns3__FindUserInSecurityDomainResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__FindUserInSecurityDomainResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__FindUserInSecurityDomainResponseType * SOAP_FMAC4 soap_instantiate_ns3__FindUserInSecurityDomainResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__FindUserInSecurityDomainResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__FindUserInSecurityDomainRequestType
#define SOAP_TYPE_ns3__FindUserInSecurityDomainRequestType (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__FindUserInSecurityDomainRequestType(struct soap*, const char*, int, const ns3__FindUserInSecurityDomainRequestType *, const char*);
SOAP_FMAC3 ns3__FindUserInSecurityDomainRequestType * SOAP_FMAC4 soap_get_ns3__FindUserInSecurityDomainRequestType(struct soap*, ns3__FindUserInSecurityDomainRequestType *, const char*, const char*);
SOAP_FMAC3 ns3__FindUserInSecurityDomainRequestType * SOAP_FMAC4 soap_in_ns3__FindUserInSecurityDomainRequestType(struct soap*, const char*, ns3__FindUserInSecurityDomainRequestType *, const char*);

#define soap_new_ns3__FindUserInSecurityDomainRequestType(soap, n) soap_instantiate_ns3__FindUserInSecurityDomainRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__FindUserInSecurityDomainRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__FindUserInSecurityDomainRequestType * SOAP_FMAC4 soap_instantiate_ns3__FindUserInSecurityDomainRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__FindUserInSecurityDomainRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__FindUserInSessionResponseType
#define SOAP_TYPE_ns3__FindUserInSessionResponseType (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__FindUserInSessionResponseType(struct soap*, const char*, int, const ns3__FindUserInSessionResponseType *, const char*);
SOAP_FMAC3 ns3__FindUserInSessionResponseType * SOAP_FMAC4 soap_get_ns3__FindUserInSessionResponseType(struct soap*, ns3__FindUserInSessionResponseType *, const char*, const char*);
SOAP_FMAC3 ns3__FindUserInSessionResponseType * SOAP_FMAC4 soap_in_ns3__FindUserInSessionResponseType(struct soap*, const char*, ns3__FindUserInSessionResponseType *, const char*);

#define soap_new_ns3__FindUserInSessionResponseType(soap, n) soap_instantiate_ns3__FindUserInSessionResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__FindUserInSessionResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__FindUserInSessionResponseType * SOAP_FMAC4 soap_instantiate_ns3__FindUserInSessionResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__FindUserInSessionResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__FindUserInSessionRequestType
#define SOAP_TYPE_ns3__FindUserInSessionRequestType (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__FindUserInSessionRequestType(struct soap*, const char*, int, const ns3__FindUserInSessionRequestType *, const char*);
SOAP_FMAC3 ns3__FindUserInSessionRequestType * SOAP_FMAC4 soap_get_ns3__FindUserInSessionRequestType(struct soap*, ns3__FindUserInSessionRequestType *, const char*, const char*);
SOAP_FMAC3 ns3__FindUserInSessionRequestType * SOAP_FMAC4 soap_in_ns3__FindUserInSessionRequestType(struct soap*, const char*, ns3__FindUserInSessionRequestType *, const char*);

#define soap_new_ns3__FindUserInSessionRequestType(soap, n) soap_instantiate_ns3__FindUserInSessionRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__FindUserInSessionRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__FindUserInSessionRequestType * SOAP_FMAC4 soap_instantiate_ns3__FindUserInSessionRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__FindUserInSessionRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__AssertionNotValidErrorType
#define SOAP_TYPE_ns3__AssertionNotValidErrorType (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__AssertionNotValidErrorType(struct soap*, const char*, int, const ns3__AssertionNotValidErrorType *, const char*);
SOAP_FMAC3 ns3__AssertionNotValidErrorType * SOAP_FMAC4 soap_get_ns3__AssertionNotValidErrorType(struct soap*, ns3__AssertionNotValidErrorType *, const char*, const char*);
SOAP_FMAC3 ns3__AssertionNotValidErrorType * SOAP_FMAC4 soap_in_ns3__AssertionNotValidErrorType(struct soap*, const char*, ns3__AssertionNotValidErrorType *, const char*);

#define soap_new_ns3__AssertionNotValidErrorType(soap, n) soap_instantiate_ns3__AssertionNotValidErrorType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__AssertionNotValidErrorType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__AssertionNotValidErrorType * SOAP_FMAC4 soap_instantiate_ns3__AssertionNotValidErrorType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__AssertionNotValidErrorType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__SSOIdentityProviderErrorType
#define SOAP_TYPE_ns3__SSOIdentityProviderErrorType (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SSOIdentityProviderErrorType(struct soap*, const char*, int, const ns3__SSOIdentityProviderErrorType *, const char*);
SOAP_FMAC3 ns3__SSOIdentityProviderErrorType * SOAP_FMAC4 soap_get_ns3__SSOIdentityProviderErrorType(struct soap*, ns3__SSOIdentityProviderErrorType *, const char*, const char*);
SOAP_FMAC3 ns3__SSOIdentityProviderErrorType * SOAP_FMAC4 soap_in_ns3__SSOIdentityProviderErrorType(struct soap*, const char*, ns3__SSOIdentityProviderErrorType *, const char*);

#define soap_new_ns3__SSOIdentityProviderErrorType(soap, n) soap_instantiate_ns3__SSOIdentityProviderErrorType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__SSOIdentityProviderErrorType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__SSOIdentityProviderErrorType * SOAP_FMAC4 soap_instantiate_ns3__SSOIdentityProviderErrorType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__SSOIdentityProviderErrorType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__GlobalSignoffResponseType
#define SOAP_TYPE_ns3__GlobalSignoffResponseType (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__GlobalSignoffResponseType(struct soap*, const char*, int, const ns3__GlobalSignoffResponseType *, const char*);
SOAP_FMAC3 ns3__GlobalSignoffResponseType * SOAP_FMAC4 soap_get_ns3__GlobalSignoffResponseType(struct soap*, ns3__GlobalSignoffResponseType *, const char*, const char*);
SOAP_FMAC3 ns3__GlobalSignoffResponseType * SOAP_FMAC4 soap_in_ns3__GlobalSignoffResponseType(struct soap*, const char*, ns3__GlobalSignoffResponseType *, const char*);

#define soap_new_ns3__GlobalSignoffResponseType(soap, n) soap_instantiate_ns3__GlobalSignoffResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__GlobalSignoffResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__GlobalSignoffResponseType * SOAP_FMAC4 soap_instantiate_ns3__GlobalSignoffResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__GlobalSignoffResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__GlobalSignoffRequestType
#define SOAP_TYPE_ns3__GlobalSignoffRequestType (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__GlobalSignoffRequestType(struct soap*, const char*, int, const ns3__GlobalSignoffRequestType *, const char*);
SOAP_FMAC3 ns3__GlobalSignoffRequestType * SOAP_FMAC4 soap_get_ns3__GlobalSignoffRequestType(struct soap*, ns3__GlobalSignoffRequestType *, const char*, const char*);
SOAP_FMAC3 ns3__GlobalSignoffRequestType * SOAP_FMAC4 soap_in_ns3__GlobalSignoffRequestType(struct soap*, const char*, ns3__GlobalSignoffRequestType *, const char*);

#define soap_new_ns3__GlobalSignoffRequestType(soap, n) soap_instantiate_ns3__GlobalSignoffRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__GlobalSignoffRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__GlobalSignoffRequestType * SOAP_FMAC4 soap_instantiate_ns3__GlobalSignoffRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__GlobalSignoffRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__AssertIdentityWithSimpleAuthenticationResponseType
#define SOAP_TYPE_ns3__AssertIdentityWithSimpleAuthenticationResponseType (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__AssertIdentityWithSimpleAuthenticationResponseType(struct soap*, const char*, int, const ns3__AssertIdentityWithSimpleAuthenticationResponseType *, const char*);
SOAP_FMAC3 ns3__AssertIdentityWithSimpleAuthenticationResponseType * SOAP_FMAC4 soap_get_ns3__AssertIdentityWithSimpleAuthenticationResponseType(struct soap*, ns3__AssertIdentityWithSimpleAuthenticationResponseType *, const char*, const char*);
SOAP_FMAC3 ns3__AssertIdentityWithSimpleAuthenticationResponseType * SOAP_FMAC4 soap_in_ns3__AssertIdentityWithSimpleAuthenticationResponseType(struct soap*, const char*, ns3__AssertIdentityWithSimpleAuthenticationResponseType *, const char*);

#define soap_new_ns3__AssertIdentityWithSimpleAuthenticationResponseType(soap, n) soap_instantiate_ns3__AssertIdentityWithSimpleAuthenticationResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__AssertIdentityWithSimpleAuthenticationResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__AssertIdentityWithSimpleAuthenticationResponseType * SOAP_FMAC4 soap_instantiate_ns3__AssertIdentityWithSimpleAuthenticationResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__AssertIdentityWithSimpleAuthenticationResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__AssertIdentityWithSimpleAuthenticationRequestType
#define SOAP_TYPE_ns3__AssertIdentityWithSimpleAuthenticationRequestType (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__AssertIdentityWithSimpleAuthenticationRequestType(struct soap*, const char*, int, const ns3__AssertIdentityWithSimpleAuthenticationRequestType *, const char*);
SOAP_FMAC3 ns3__AssertIdentityWithSimpleAuthenticationRequestType * SOAP_FMAC4 soap_get_ns3__AssertIdentityWithSimpleAuthenticationRequestType(struct soap*, ns3__AssertIdentityWithSimpleAuthenticationRequestType *, const char*, const char*);
SOAP_FMAC3 ns3__AssertIdentityWithSimpleAuthenticationRequestType * SOAP_FMAC4 soap_in_ns3__AssertIdentityWithSimpleAuthenticationRequestType(struct soap*, const char*, ns3__AssertIdentityWithSimpleAuthenticationRequestType *, const char*);

#define soap_new_ns3__AssertIdentityWithSimpleAuthenticationRequestType(soap, n) soap_instantiate_ns3__AssertIdentityWithSimpleAuthenticationRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__AssertIdentityWithSimpleAuthenticationRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__AssertIdentityWithSimpleAuthenticationRequestType * SOAP_FMAC4 soap_instantiate_ns3__AssertIdentityWithSimpleAuthenticationRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__AssertIdentityWithSimpleAuthenticationRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__ResolveAuthenticationAssertionResponseType
#define SOAP_TYPE_ns3__ResolveAuthenticationAssertionResponseType (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__ResolveAuthenticationAssertionResponseType(struct soap*, const char*, int, const ns3__ResolveAuthenticationAssertionResponseType *, const char*);
SOAP_FMAC3 ns3__ResolveAuthenticationAssertionResponseType * SOAP_FMAC4 soap_get_ns3__ResolveAuthenticationAssertionResponseType(struct soap*, ns3__ResolveAuthenticationAssertionResponseType *, const char*, const char*);
SOAP_FMAC3 ns3__ResolveAuthenticationAssertionResponseType * SOAP_FMAC4 soap_in_ns3__ResolveAuthenticationAssertionResponseType(struct soap*, const char*, ns3__ResolveAuthenticationAssertionResponseType *, const char*);

#define soap_new_ns3__ResolveAuthenticationAssertionResponseType(soap, n) soap_instantiate_ns3__ResolveAuthenticationAssertionResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__ResolveAuthenticationAssertionResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__ResolveAuthenticationAssertionResponseType * SOAP_FMAC4 soap_instantiate_ns3__ResolveAuthenticationAssertionResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__ResolveAuthenticationAssertionResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__ResolveAuthenticationAssertionRequestType
#define SOAP_TYPE_ns3__ResolveAuthenticationAssertionRequestType (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__ResolveAuthenticationAssertionRequestType(struct soap*, const char*, int, const ns3__ResolveAuthenticationAssertionRequestType *, const char*);
SOAP_FMAC3 ns3__ResolveAuthenticationAssertionRequestType * SOAP_FMAC4 soap_get_ns3__ResolveAuthenticationAssertionRequestType(struct soap*, ns3__ResolveAuthenticationAssertionRequestType *, const char*, const char*);
SOAP_FMAC3 ns3__ResolveAuthenticationAssertionRequestType * SOAP_FMAC4 soap_in_ns3__ResolveAuthenticationAssertionRequestType(struct soap*, const char*, ns3__ResolveAuthenticationAssertionRequestType *, const char*);

#define soap_new_ns3__ResolveAuthenticationAssertionRequestType(soap, n) soap_instantiate_ns3__ResolveAuthenticationAssertionRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns3__ResolveAuthenticationAssertionRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns3__ResolveAuthenticationAssertionRequestType * SOAP_FMAC4 soap_instantiate_ns3__ResolveAuthenticationAssertionRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__ResolveAuthenticationAssertionRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (98)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (97)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (95)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (94)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns6__getSession
#define SOAP_TYPE___ns6__getSession (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns6__getSession(struct soap*, struct __ns6__getSession *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns6__getSession(struct soap*, const struct __ns6__getSession *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns6__getSession(struct soap*, const struct __ns6__getSession *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns6__getSession(struct soap*, const char*, int, const struct __ns6__getSession *, const char*);
SOAP_FMAC3 struct __ns6__getSession * SOAP_FMAC4 soap_get___ns6__getSession(struct soap*, struct __ns6__getSession *, const char*, const char*);
SOAP_FMAC3 struct __ns6__getSession * SOAP_FMAC4 soap_in___ns6__getSession(struct soap*, const char*, struct __ns6__getSession *, const char*);

#define soap_new___ns6__getSession(soap, n) soap_instantiate___ns6__getSession(soap, n, NULL, NULL, NULL)


#define soap_delete___ns6__getSession(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns6__getSession * SOAP_FMAC4 soap_instantiate___ns6__getSession(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns6__getSession(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns6__accessSession
#define SOAP_TYPE___ns6__accessSession (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns6__accessSession(struct soap*, struct __ns6__accessSession *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns6__accessSession(struct soap*, const struct __ns6__accessSession *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns6__accessSession(struct soap*, const struct __ns6__accessSession *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns6__accessSession(struct soap*, const char*, int, const struct __ns6__accessSession *, const char*);
SOAP_FMAC3 struct __ns6__accessSession * SOAP_FMAC4 soap_get___ns6__accessSession(struct soap*, struct __ns6__accessSession *, const char*, const char*);
SOAP_FMAC3 struct __ns6__accessSession * SOAP_FMAC4 soap_in___ns6__accessSession(struct soap*, const char*, struct __ns6__accessSession *, const char*);

#define soap_new___ns6__accessSession(soap, n) soap_instantiate___ns6__accessSession(soap, n, NULL, NULL, NULL)


#define soap_delete___ns6__accessSession(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns6__accessSession * SOAP_FMAC4 soap_instantiate___ns6__accessSession(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns6__accessSession(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns5__userExists
#define SOAP_TYPE___ns5__userExists (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns5__userExists(struct soap*, struct __ns5__userExists *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns5__userExists(struct soap*, const struct __ns5__userExists *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns5__userExists(struct soap*, const struct __ns5__userExists *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns5__userExists(struct soap*, const char*, int, const struct __ns5__userExists *, const char*);
SOAP_FMAC3 struct __ns5__userExists * SOAP_FMAC4 soap_get___ns5__userExists(struct soap*, struct __ns5__userExists *, const char*, const char*);
SOAP_FMAC3 struct __ns5__userExists * SOAP_FMAC4 soap_in___ns5__userExists(struct soap*, const char*, struct __ns5__userExists *, const char*);

#define soap_new___ns5__userExists(soap, n) soap_instantiate___ns5__userExists(soap, n, NULL, NULL, NULL)


#define soap_delete___ns5__userExists(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns5__userExists * SOAP_FMAC4 soap_instantiate___ns5__userExists(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns5__userExists(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns5__findRolesBySSOSessionId
#define SOAP_TYPE___ns5__findRolesBySSOSessionId (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns5__findRolesBySSOSessionId(struct soap*, struct __ns5__findRolesBySSOSessionId *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns5__findRolesBySSOSessionId(struct soap*, const struct __ns5__findRolesBySSOSessionId *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns5__findRolesBySSOSessionId(struct soap*, const struct __ns5__findRolesBySSOSessionId *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns5__findRolesBySSOSessionId(struct soap*, const char*, int, const struct __ns5__findRolesBySSOSessionId *, const char*);
SOAP_FMAC3 struct __ns5__findRolesBySSOSessionId * SOAP_FMAC4 soap_get___ns5__findRolesBySSOSessionId(struct soap*, struct __ns5__findRolesBySSOSessionId *, const char*, const char*);
SOAP_FMAC3 struct __ns5__findRolesBySSOSessionId * SOAP_FMAC4 soap_in___ns5__findRolesBySSOSessionId(struct soap*, const char*, struct __ns5__findRolesBySSOSessionId *, const char*);

#define soap_new___ns5__findRolesBySSOSessionId(soap, n) soap_instantiate___ns5__findRolesBySSOSessionId(soap, n, NULL, NULL, NULL)


#define soap_delete___ns5__findRolesBySSOSessionId(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns5__findRolesBySSOSessionId * SOAP_FMAC4 soap_instantiate___ns5__findRolesBySSOSessionId(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns5__findRolesBySSOSessionId(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns5__findUserInSecurityDomain
#define SOAP_TYPE___ns5__findUserInSecurityDomain (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns5__findUserInSecurityDomain(struct soap*, struct __ns5__findUserInSecurityDomain *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns5__findUserInSecurityDomain(struct soap*, const struct __ns5__findUserInSecurityDomain *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns5__findUserInSecurityDomain(struct soap*, const struct __ns5__findUserInSecurityDomain *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns5__findUserInSecurityDomain(struct soap*, const char*, int, const struct __ns5__findUserInSecurityDomain *, const char*);
SOAP_FMAC3 struct __ns5__findUserInSecurityDomain * SOAP_FMAC4 soap_get___ns5__findUserInSecurityDomain(struct soap*, struct __ns5__findUserInSecurityDomain *, const char*, const char*);
SOAP_FMAC3 struct __ns5__findUserInSecurityDomain * SOAP_FMAC4 soap_in___ns5__findUserInSecurityDomain(struct soap*, const char*, struct __ns5__findUserInSecurityDomain *, const char*);

#define soap_new___ns5__findUserInSecurityDomain(soap, n) soap_instantiate___ns5__findUserInSecurityDomain(soap, n, NULL, NULL, NULL)


#define soap_delete___ns5__findUserInSecurityDomain(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns5__findUserInSecurityDomain * SOAP_FMAC4 soap_instantiate___ns5__findUserInSecurityDomain(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns5__findUserInSecurityDomain(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns5__findUserInSession
#define SOAP_TYPE___ns5__findUserInSession (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns5__findUserInSession(struct soap*, struct __ns5__findUserInSession *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns5__findUserInSession(struct soap*, const struct __ns5__findUserInSession *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns5__findUserInSession(struct soap*, const struct __ns5__findUserInSession *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns5__findUserInSession(struct soap*, const char*, int, const struct __ns5__findUserInSession *, const char*);
SOAP_FMAC3 struct __ns5__findUserInSession * SOAP_FMAC4 soap_get___ns5__findUserInSession(struct soap*, struct __ns5__findUserInSession *, const char*, const char*);
SOAP_FMAC3 struct __ns5__findUserInSession * SOAP_FMAC4 soap_in___ns5__findUserInSession(struct soap*, const char*, struct __ns5__findUserInSession *, const char*);

#define soap_new___ns5__findUserInSession(soap, n) soap_instantiate___ns5__findUserInSession(soap, n, NULL, NULL, NULL)


#define soap_delete___ns5__findUserInSession(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns5__findUserInSession * SOAP_FMAC4 soap_instantiate___ns5__findUserInSession(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns5__findUserInSession(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__globalSignoff
#define SOAP_TYPE___ns4__globalSignoff (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__globalSignoff(struct soap*, struct __ns4__globalSignoff *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__globalSignoff(struct soap*, const struct __ns4__globalSignoff *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__globalSignoff(struct soap*, const struct __ns4__globalSignoff *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__globalSignoff(struct soap*, const char*, int, const struct __ns4__globalSignoff *, const char*);
SOAP_FMAC3 struct __ns4__globalSignoff * SOAP_FMAC4 soap_get___ns4__globalSignoff(struct soap*, struct __ns4__globalSignoff *, const char*, const char*);
SOAP_FMAC3 struct __ns4__globalSignoff * SOAP_FMAC4 soap_in___ns4__globalSignoff(struct soap*, const char*, struct __ns4__globalSignoff *, const char*);

#define soap_new___ns4__globalSignoff(soap, n) soap_instantiate___ns4__globalSignoff(soap, n, NULL, NULL, NULL)


#define soap_delete___ns4__globalSignoff(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns4__globalSignoff * SOAP_FMAC4 soap_instantiate___ns4__globalSignoff(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__globalSignoff(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__assertIdentityWithSimpleAuthentication
#define SOAP_TYPE___ns4__assertIdentityWithSimpleAuthentication (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__assertIdentityWithSimpleAuthentication(struct soap*, struct __ns4__assertIdentityWithSimpleAuthentication *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__assertIdentityWithSimpleAuthentication(struct soap*, const struct __ns4__assertIdentityWithSimpleAuthentication *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__assertIdentityWithSimpleAuthentication(struct soap*, const struct __ns4__assertIdentityWithSimpleAuthentication *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__assertIdentityWithSimpleAuthentication(struct soap*, const char*, int, const struct __ns4__assertIdentityWithSimpleAuthentication *, const char*);
SOAP_FMAC3 struct __ns4__assertIdentityWithSimpleAuthentication * SOAP_FMAC4 soap_get___ns4__assertIdentityWithSimpleAuthentication(struct soap*, struct __ns4__assertIdentityWithSimpleAuthentication *, const char*, const char*);
SOAP_FMAC3 struct __ns4__assertIdentityWithSimpleAuthentication * SOAP_FMAC4 soap_in___ns4__assertIdentityWithSimpleAuthentication(struct soap*, const char*, struct __ns4__assertIdentityWithSimpleAuthentication *, const char*);

#define soap_new___ns4__assertIdentityWithSimpleAuthentication(soap, n) soap_instantiate___ns4__assertIdentityWithSimpleAuthentication(soap, n, NULL, NULL, NULL)


#define soap_delete___ns4__assertIdentityWithSimpleAuthentication(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns4__assertIdentityWithSimpleAuthentication * SOAP_FMAC4 soap_instantiate___ns4__assertIdentityWithSimpleAuthentication(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__assertIdentityWithSimpleAuthentication(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__resolveAuthenticationAssertion
#define SOAP_TYPE___ns4__resolveAuthenticationAssertion (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__resolveAuthenticationAssertion(struct soap*, struct __ns4__resolveAuthenticationAssertion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__resolveAuthenticationAssertion(struct soap*, const struct __ns4__resolveAuthenticationAssertion *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__resolveAuthenticationAssertion(struct soap*, const struct __ns4__resolveAuthenticationAssertion *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__resolveAuthenticationAssertion(struct soap*, const char*, int, const struct __ns4__resolveAuthenticationAssertion *, const char*);
SOAP_FMAC3 struct __ns4__resolveAuthenticationAssertion * SOAP_FMAC4 soap_get___ns4__resolveAuthenticationAssertion(struct soap*, struct __ns4__resolveAuthenticationAssertion *, const char*, const char*);
SOAP_FMAC3 struct __ns4__resolveAuthenticationAssertion * SOAP_FMAC4 soap_in___ns4__resolveAuthenticationAssertion(struct soap*, const char*, struct __ns4__resolveAuthenticationAssertion *, const char*);

#define soap_new___ns4__resolveAuthenticationAssertion(soap, n) soap_instantiate___ns4__resolveAuthenticationAssertion(soap, n, NULL, NULL, NULL)


#define soap_delete___ns4__resolveAuthenticationAssertion(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns4__resolveAuthenticationAssertion * SOAP_FMAC4 soap_instantiate___ns4__resolveAuthenticationAssertion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__resolveAuthenticationAssertion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (100)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (99)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (96)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons3__SessionResponseType
#define SOAP_TYPE_PointerTons3__SessionResponseType (91)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__SessionResponseType(struct soap*, ns3__SessionResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__SessionResponseType(struct soap*, ns3__SessionResponseType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__SessionResponseType(struct soap*, const char *, int, ns3__SessionResponseType *const*, const char *);
SOAP_FMAC3 ns3__SessionResponseType ** SOAP_FMAC4 soap_get_PointerTons3__SessionResponseType(struct soap*, ns3__SessionResponseType **, const char*, const char*);
SOAP_FMAC3 ns3__SessionResponseType ** SOAP_FMAC4 soap_in_PointerTons3__SessionResponseType(struct soap*, const char*, ns3__SessionResponseType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__SessionRequestType
#define SOAP_TYPE_PointerTons3__SessionRequestType (90)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__SessionRequestType(struct soap*, ns3__SessionRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__SessionRequestType(struct soap*, ns3__SessionRequestType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__SessionRequestType(struct soap*, const char *, int, ns3__SessionRequestType *const*, const char *);
SOAP_FMAC3 ns3__SessionRequestType ** SOAP_FMAC4 soap_get_PointerTons3__SessionRequestType(struct soap*, ns3__SessionRequestType **, const char*, const char*);
SOAP_FMAC3 ns3__SessionRequestType ** SOAP_FMAC4 soap_in_PointerTons3__SessionRequestType(struct soap*, const char*, ns3__SessionRequestType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__AccessSessionResponseType
#define SOAP_TYPE_PointerTons3__AccessSessionResponseType (87)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__AccessSessionResponseType(struct soap*, ns3__AccessSessionResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__AccessSessionResponseType(struct soap*, ns3__AccessSessionResponseType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__AccessSessionResponseType(struct soap*, const char *, int, ns3__AccessSessionResponseType *const*, const char *);
SOAP_FMAC3 ns3__AccessSessionResponseType ** SOAP_FMAC4 soap_get_PointerTons3__AccessSessionResponseType(struct soap*, ns3__AccessSessionResponseType **, const char*, const char*);
SOAP_FMAC3 ns3__AccessSessionResponseType ** SOAP_FMAC4 soap_in_PointerTons3__AccessSessionResponseType(struct soap*, const char*, ns3__AccessSessionResponseType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__AccessSessionRequestType
#define SOAP_TYPE_PointerTons3__AccessSessionRequestType (86)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__AccessSessionRequestType(struct soap*, ns3__AccessSessionRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__AccessSessionRequestType(struct soap*, ns3__AccessSessionRequestType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__AccessSessionRequestType(struct soap*, const char *, int, ns3__AccessSessionRequestType *const*, const char *);
SOAP_FMAC3 ns3__AccessSessionRequestType ** SOAP_FMAC4 soap_get_PointerTons3__AccessSessionRequestType(struct soap*, ns3__AccessSessionRequestType **, const char*, const char*);
SOAP_FMAC3 ns3__AccessSessionRequestType ** SOAP_FMAC4 soap_in_PointerTons3__AccessSessionRequestType(struct soap*, const char*, ns3__AccessSessionRequestType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__UserExistsResponseType
#define SOAP_TYPE_PointerTons3__UserExistsResponseType (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__UserExistsResponseType(struct soap*, ns3__UserExistsResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__UserExistsResponseType(struct soap*, ns3__UserExistsResponseType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__UserExistsResponseType(struct soap*, const char *, int, ns3__UserExistsResponseType *const*, const char *);
SOAP_FMAC3 ns3__UserExistsResponseType ** SOAP_FMAC4 soap_get_PointerTons3__UserExistsResponseType(struct soap*, ns3__UserExistsResponseType **, const char*, const char*);
SOAP_FMAC3 ns3__UserExistsResponseType ** SOAP_FMAC4 soap_in_PointerTons3__UserExistsResponseType(struct soap*, const char*, ns3__UserExistsResponseType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__UserExistsRequestType
#define SOAP_TYPE_PointerTons3__UserExistsRequestType (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__UserExistsRequestType(struct soap*, ns3__UserExistsRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__UserExistsRequestType(struct soap*, ns3__UserExistsRequestType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__UserExistsRequestType(struct soap*, const char *, int, ns3__UserExistsRequestType *const*, const char *);
SOAP_FMAC3 ns3__UserExistsRequestType ** SOAP_FMAC4 soap_get_PointerTons3__UserExistsRequestType(struct soap*, ns3__UserExistsRequestType **, const char*, const char*);
SOAP_FMAC3 ns3__UserExistsRequestType ** SOAP_FMAC4 soap_in_PointerTons3__UserExistsRequestType(struct soap*, const char*, ns3__UserExistsRequestType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__FindRolesBySSOSessionIdResponseType
#define SOAP_TYPE_PointerTons3__FindRolesBySSOSessionIdResponseType (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__FindRolesBySSOSessionIdResponseType(struct soap*, ns3__FindRolesBySSOSessionIdResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__FindRolesBySSOSessionIdResponseType(struct soap*, ns3__FindRolesBySSOSessionIdResponseType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__FindRolesBySSOSessionIdResponseType(struct soap*, const char *, int, ns3__FindRolesBySSOSessionIdResponseType *const*, const char *);
SOAP_FMAC3 ns3__FindRolesBySSOSessionIdResponseType ** SOAP_FMAC4 soap_get_PointerTons3__FindRolesBySSOSessionIdResponseType(struct soap*, ns3__FindRolesBySSOSessionIdResponseType **, const char*, const char*);
SOAP_FMAC3 ns3__FindRolesBySSOSessionIdResponseType ** SOAP_FMAC4 soap_in_PointerTons3__FindRolesBySSOSessionIdResponseType(struct soap*, const char*, ns3__FindRolesBySSOSessionIdResponseType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__FindRolesBySSOSessionIdRequestType
#define SOAP_TYPE_PointerTons3__FindRolesBySSOSessionIdRequestType (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__FindRolesBySSOSessionIdRequestType(struct soap*, ns3__FindRolesBySSOSessionIdRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__FindRolesBySSOSessionIdRequestType(struct soap*, ns3__FindRolesBySSOSessionIdRequestType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__FindRolesBySSOSessionIdRequestType(struct soap*, const char *, int, ns3__FindRolesBySSOSessionIdRequestType *const*, const char *);
SOAP_FMAC3 ns3__FindRolesBySSOSessionIdRequestType ** SOAP_FMAC4 soap_get_PointerTons3__FindRolesBySSOSessionIdRequestType(struct soap*, ns3__FindRolesBySSOSessionIdRequestType **, const char*, const char*);
SOAP_FMAC3 ns3__FindRolesBySSOSessionIdRequestType ** SOAP_FMAC4 soap_in_PointerTons3__FindRolesBySSOSessionIdRequestType(struct soap*, const char*, ns3__FindRolesBySSOSessionIdRequestType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__FindUserInSecurityDomainResponseType
#define SOAP_TYPE_PointerTons3__FindUserInSecurityDomainResponseType (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__FindUserInSecurityDomainResponseType(struct soap*, ns3__FindUserInSecurityDomainResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__FindUserInSecurityDomainResponseType(struct soap*, ns3__FindUserInSecurityDomainResponseType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__FindUserInSecurityDomainResponseType(struct soap*, const char *, int, ns3__FindUserInSecurityDomainResponseType *const*, const char *);
SOAP_FMAC3 ns3__FindUserInSecurityDomainResponseType ** SOAP_FMAC4 soap_get_PointerTons3__FindUserInSecurityDomainResponseType(struct soap*, ns3__FindUserInSecurityDomainResponseType **, const char*, const char*);
SOAP_FMAC3 ns3__FindUserInSecurityDomainResponseType ** SOAP_FMAC4 soap_in_PointerTons3__FindUserInSecurityDomainResponseType(struct soap*, const char*, ns3__FindUserInSecurityDomainResponseType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__FindUserInSecurityDomainRequestType
#define SOAP_TYPE_PointerTons3__FindUserInSecurityDomainRequestType (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__FindUserInSecurityDomainRequestType(struct soap*, ns3__FindUserInSecurityDomainRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__FindUserInSecurityDomainRequestType(struct soap*, ns3__FindUserInSecurityDomainRequestType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__FindUserInSecurityDomainRequestType(struct soap*, const char *, int, ns3__FindUserInSecurityDomainRequestType *const*, const char *);
SOAP_FMAC3 ns3__FindUserInSecurityDomainRequestType ** SOAP_FMAC4 soap_get_PointerTons3__FindUserInSecurityDomainRequestType(struct soap*, ns3__FindUserInSecurityDomainRequestType **, const char*, const char*);
SOAP_FMAC3 ns3__FindUserInSecurityDomainRequestType ** SOAP_FMAC4 soap_in_PointerTons3__FindUserInSecurityDomainRequestType(struct soap*, const char*, ns3__FindUserInSecurityDomainRequestType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__FindUserInSessionResponseType
#define SOAP_TYPE_PointerTons3__FindUserInSessionResponseType (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__FindUserInSessionResponseType(struct soap*, ns3__FindUserInSessionResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__FindUserInSessionResponseType(struct soap*, ns3__FindUserInSessionResponseType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__FindUserInSessionResponseType(struct soap*, const char *, int, ns3__FindUserInSessionResponseType *const*, const char *);
SOAP_FMAC3 ns3__FindUserInSessionResponseType ** SOAP_FMAC4 soap_get_PointerTons3__FindUserInSessionResponseType(struct soap*, ns3__FindUserInSessionResponseType **, const char*, const char*);
SOAP_FMAC3 ns3__FindUserInSessionResponseType ** SOAP_FMAC4 soap_in_PointerTons3__FindUserInSessionResponseType(struct soap*, const char*, ns3__FindUserInSessionResponseType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__FindUserInSessionRequestType
#define SOAP_TYPE_PointerTons3__FindUserInSessionRequestType (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__FindUserInSessionRequestType(struct soap*, ns3__FindUserInSessionRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__FindUserInSessionRequestType(struct soap*, ns3__FindUserInSessionRequestType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__FindUserInSessionRequestType(struct soap*, const char *, int, ns3__FindUserInSessionRequestType *const*, const char *);
SOAP_FMAC3 ns3__FindUserInSessionRequestType ** SOAP_FMAC4 soap_get_PointerTons3__FindUserInSessionRequestType(struct soap*, ns3__FindUserInSessionRequestType **, const char*, const char*);
SOAP_FMAC3 ns3__FindUserInSessionRequestType ** SOAP_FMAC4 soap_in_PointerTons3__FindUserInSessionRequestType(struct soap*, const char*, ns3__FindUserInSessionRequestType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__GlobalSignoffResponseType
#define SOAP_TYPE_PointerTons3__GlobalSignoffResponseType (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__GlobalSignoffResponseType(struct soap*, ns3__GlobalSignoffResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__GlobalSignoffResponseType(struct soap*, ns3__GlobalSignoffResponseType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__GlobalSignoffResponseType(struct soap*, const char *, int, ns3__GlobalSignoffResponseType *const*, const char *);
SOAP_FMAC3 ns3__GlobalSignoffResponseType ** SOAP_FMAC4 soap_get_PointerTons3__GlobalSignoffResponseType(struct soap*, ns3__GlobalSignoffResponseType **, const char*, const char*);
SOAP_FMAC3 ns3__GlobalSignoffResponseType ** SOAP_FMAC4 soap_in_PointerTons3__GlobalSignoffResponseType(struct soap*, const char*, ns3__GlobalSignoffResponseType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__GlobalSignoffRequestType
#define SOAP_TYPE_PointerTons3__GlobalSignoffRequestType (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__GlobalSignoffRequestType(struct soap*, ns3__GlobalSignoffRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__GlobalSignoffRequestType(struct soap*, ns3__GlobalSignoffRequestType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__GlobalSignoffRequestType(struct soap*, const char *, int, ns3__GlobalSignoffRequestType *const*, const char *);
SOAP_FMAC3 ns3__GlobalSignoffRequestType ** SOAP_FMAC4 soap_get_PointerTons3__GlobalSignoffRequestType(struct soap*, ns3__GlobalSignoffRequestType **, const char*, const char*);
SOAP_FMAC3 ns3__GlobalSignoffRequestType ** SOAP_FMAC4 soap_in_PointerTons3__GlobalSignoffRequestType(struct soap*, const char*, ns3__GlobalSignoffRequestType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__AssertIdentityWithSimpleAuthenticationResponseType
#define SOAP_TYPE_PointerTons3__AssertIdentityWithSimpleAuthenticationResponseType (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__AssertIdentityWithSimpleAuthenticationResponseType(struct soap*, ns3__AssertIdentityWithSimpleAuthenticationResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__AssertIdentityWithSimpleAuthenticationResponseType(struct soap*, ns3__AssertIdentityWithSimpleAuthenticationResponseType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__AssertIdentityWithSimpleAuthenticationResponseType(struct soap*, const char *, int, ns3__AssertIdentityWithSimpleAuthenticationResponseType *const*, const char *);
SOAP_FMAC3 ns3__AssertIdentityWithSimpleAuthenticationResponseType ** SOAP_FMAC4 soap_get_PointerTons3__AssertIdentityWithSimpleAuthenticationResponseType(struct soap*, ns3__AssertIdentityWithSimpleAuthenticationResponseType **, const char*, const char*);
SOAP_FMAC3 ns3__AssertIdentityWithSimpleAuthenticationResponseType ** SOAP_FMAC4 soap_in_PointerTons3__AssertIdentityWithSimpleAuthenticationResponseType(struct soap*, const char*, ns3__AssertIdentityWithSimpleAuthenticationResponseType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__AssertIdentityWithSimpleAuthenticationRequestType
#define SOAP_TYPE_PointerTons3__AssertIdentityWithSimpleAuthenticationRequestType (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__AssertIdentityWithSimpleAuthenticationRequestType(struct soap*, ns3__AssertIdentityWithSimpleAuthenticationRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__AssertIdentityWithSimpleAuthenticationRequestType(struct soap*, ns3__AssertIdentityWithSimpleAuthenticationRequestType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__AssertIdentityWithSimpleAuthenticationRequestType(struct soap*, const char *, int, ns3__AssertIdentityWithSimpleAuthenticationRequestType *const*, const char *);
SOAP_FMAC3 ns3__AssertIdentityWithSimpleAuthenticationRequestType ** SOAP_FMAC4 soap_get_PointerTons3__AssertIdentityWithSimpleAuthenticationRequestType(struct soap*, ns3__AssertIdentityWithSimpleAuthenticationRequestType **, const char*, const char*);
SOAP_FMAC3 ns3__AssertIdentityWithSimpleAuthenticationRequestType ** SOAP_FMAC4 soap_in_PointerTons3__AssertIdentityWithSimpleAuthenticationRequestType(struct soap*, const char*, ns3__AssertIdentityWithSimpleAuthenticationRequestType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__ResolveAuthenticationAssertionResponseType
#define SOAP_TYPE_PointerTons3__ResolveAuthenticationAssertionResponseType (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__ResolveAuthenticationAssertionResponseType(struct soap*, ns3__ResolveAuthenticationAssertionResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__ResolveAuthenticationAssertionResponseType(struct soap*, ns3__ResolveAuthenticationAssertionResponseType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__ResolveAuthenticationAssertionResponseType(struct soap*, const char *, int, ns3__ResolveAuthenticationAssertionResponseType *const*, const char *);
SOAP_FMAC3 ns3__ResolveAuthenticationAssertionResponseType ** SOAP_FMAC4 soap_get_PointerTons3__ResolveAuthenticationAssertionResponseType(struct soap*, ns3__ResolveAuthenticationAssertionResponseType **, const char*, const char*);
SOAP_FMAC3 ns3__ResolveAuthenticationAssertionResponseType ** SOAP_FMAC4 soap_in_PointerTons3__ResolveAuthenticationAssertionResponseType(struct soap*, const char*, ns3__ResolveAuthenticationAssertionResponseType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__ResolveAuthenticationAssertionRequestType
#define SOAP_TYPE_PointerTons3__ResolveAuthenticationAssertionRequestType (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__ResolveAuthenticationAssertionRequestType(struct soap*, ns3__ResolveAuthenticationAssertionRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__ResolveAuthenticationAssertionRequestType(struct soap*, ns3__ResolveAuthenticationAssertionRequestType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__ResolveAuthenticationAssertionRequestType(struct soap*, const char *, int, ns3__ResolveAuthenticationAssertionRequestType *const*, const char *);
SOAP_FMAC3 ns3__ResolveAuthenticationAssertionRequestType ** SOAP_FMAC4 soap_get_PointerTons3__ResolveAuthenticationAssertionRequestType(struct soap*, ns3__ResolveAuthenticationAssertionRequestType **, const char*, const char*);
SOAP_FMAC3 ns3__ResolveAuthenticationAssertionRequestType ** SOAP_FMAC4 soap_in_PointerTons3__ResolveAuthenticationAssertionRequestType(struct soap*, const char*, ns3__ResolveAuthenticationAssertionRequestType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__SSOSessionErrorType
#define SOAP_TYPE_PointerTons3__SSOSessionErrorType (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__SSOSessionErrorType(struct soap*, ns3__SSOSessionErrorType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__SSOSessionErrorType(struct soap*, ns3__SSOSessionErrorType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__SSOSessionErrorType(struct soap*, const char *, int, ns3__SSOSessionErrorType *const*, const char *);
SOAP_FMAC3 ns3__SSOSessionErrorType ** SOAP_FMAC4 soap_get_PointerTons3__SSOSessionErrorType(struct soap*, ns3__SSOSessionErrorType **, const char*, const char*);
SOAP_FMAC3 ns3__SSOSessionErrorType ** SOAP_FMAC4 soap_in_PointerTons3__SSOSessionErrorType(struct soap*, const char*, ns3__SSOSessionErrorType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__NoSuchSessionErrorType
#define SOAP_TYPE_PointerTons3__NoSuchSessionErrorType (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__NoSuchSessionErrorType(struct soap*, ns3__NoSuchSessionErrorType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__NoSuchSessionErrorType(struct soap*, ns3__NoSuchSessionErrorType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__NoSuchSessionErrorType(struct soap*, const char *, int, ns3__NoSuchSessionErrorType *const*, const char *);
SOAP_FMAC3 ns3__NoSuchSessionErrorType ** SOAP_FMAC4 soap_get_PointerTons3__NoSuchSessionErrorType(struct soap*, ns3__NoSuchSessionErrorType **, const char*, const char*);
SOAP_FMAC3 ns3__NoSuchSessionErrorType ** SOAP_FMAC4 soap_in_PointerTons3__NoSuchSessionErrorType(struct soap*, const char*, ns3__NoSuchSessionErrorType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__SSOIdentityManagerErrorType
#define SOAP_TYPE_PointerTons3__SSOIdentityManagerErrorType (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__SSOIdentityManagerErrorType(struct soap*, ns3__SSOIdentityManagerErrorType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__SSOIdentityManagerErrorType(struct soap*, ns3__SSOIdentityManagerErrorType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__SSOIdentityManagerErrorType(struct soap*, const char *, int, ns3__SSOIdentityManagerErrorType *const*, const char *);
SOAP_FMAC3 ns3__SSOIdentityManagerErrorType ** SOAP_FMAC4 soap_get_PointerTons3__SSOIdentityManagerErrorType(struct soap*, ns3__SSOIdentityManagerErrorType **, const char*, const char*);
SOAP_FMAC3 ns3__SSOIdentityManagerErrorType ** SOAP_FMAC4 soap_in_PointerTons3__SSOIdentityManagerErrorType(struct soap*, const char*, ns3__SSOIdentityManagerErrorType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__NoSuchUserErrorType
#define SOAP_TYPE_PointerTons3__NoSuchUserErrorType (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__NoSuchUserErrorType(struct soap*, ns3__NoSuchUserErrorType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__NoSuchUserErrorType(struct soap*, ns3__NoSuchUserErrorType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__NoSuchUserErrorType(struct soap*, const char *, int, ns3__NoSuchUserErrorType *const*, const char *);
SOAP_FMAC3 ns3__NoSuchUserErrorType ** SOAP_FMAC4 soap_get_PointerTons3__NoSuchUserErrorType(struct soap*, ns3__NoSuchUserErrorType **, const char*, const char*);
SOAP_FMAC3 ns3__NoSuchUserErrorType ** SOAP_FMAC4 soap_in_PointerTons3__NoSuchUserErrorType(struct soap*, const char*, ns3__NoSuchUserErrorType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__InvalidSessionErrorType
#define SOAP_TYPE_PointerTons3__InvalidSessionErrorType (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__InvalidSessionErrorType(struct soap*, ns3__InvalidSessionErrorType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__InvalidSessionErrorType(struct soap*, ns3__InvalidSessionErrorType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__InvalidSessionErrorType(struct soap*, const char *, int, ns3__InvalidSessionErrorType *const*, const char *);
SOAP_FMAC3 ns3__InvalidSessionErrorType ** SOAP_FMAC4 soap_get_PointerTons3__InvalidSessionErrorType(struct soap*, ns3__InvalidSessionErrorType **, const char*, const char*);
SOAP_FMAC3 ns3__InvalidSessionErrorType ** SOAP_FMAC4 soap_in_PointerTons3__InvalidSessionErrorType(struct soap*, const char*, ns3__InvalidSessionErrorType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__SSOIdentityProviderErrorType
#define SOAP_TYPE_PointerTons3__SSOIdentityProviderErrorType (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__SSOIdentityProviderErrorType(struct soap*, ns3__SSOIdentityProviderErrorType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__SSOIdentityProviderErrorType(struct soap*, ns3__SSOIdentityProviderErrorType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__SSOIdentityProviderErrorType(struct soap*, const char *, int, ns3__SSOIdentityProviderErrorType *const*, const char *);
SOAP_FMAC3 ns3__SSOIdentityProviderErrorType ** SOAP_FMAC4 soap_get_PointerTons3__SSOIdentityProviderErrorType(struct soap*, ns3__SSOIdentityProviderErrorType **, const char*, const char*);
SOAP_FMAC3 ns3__SSOIdentityProviderErrorType ** SOAP_FMAC4 soap_in_PointerTons3__SSOIdentityProviderErrorType(struct soap*, const char*, ns3__SSOIdentityProviderErrorType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__AssertionNotValidErrorType
#define SOAP_TYPE_PointerTons3__AssertionNotValidErrorType (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__AssertionNotValidErrorType(struct soap*, ns3__AssertionNotValidErrorType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__AssertionNotValidErrorType(struct soap*, ns3__AssertionNotValidErrorType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__AssertionNotValidErrorType(struct soap*, const char *, int, ns3__AssertionNotValidErrorType *const*, const char *);
SOAP_FMAC3 ns3__AssertionNotValidErrorType ** SOAP_FMAC4 soap_get_PointerTons3__AssertionNotValidErrorType(struct soap*, ns3__AssertionNotValidErrorType **, const char*, const char*);
SOAP_FMAC3 ns3__AssertionNotValidErrorType ** SOAP_FMAC4 soap_in_PointerTons3__AssertionNotValidErrorType(struct soap*, const char*, ns3__AssertionNotValidErrorType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__SSONameValuePairType
#define SOAP_TYPE_PointerTons3__SSONameValuePairType (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__SSONameValuePairType(struct soap*, ns3__SSONameValuePairType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__SSONameValuePairType(struct soap*, ns3__SSONameValuePairType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__SSONameValuePairType(struct soap*, const char *, int, ns3__SSONameValuePairType *const*, const char *);
SOAP_FMAC3 ns3__SSONameValuePairType ** SOAP_FMAC4 soap_get_PointerTons3__SSONameValuePairType(struct soap*, ns3__SSONameValuePairType **, const char*, const char*);
SOAP_FMAC3 ns3__SSONameValuePairType ** SOAP_FMAC4 soap_in_PointerTons3__SSONameValuePairType(struct soap*, const char*, ns3__SSONameValuePairType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__SSOSessionType
#define SOAP_TYPE_PointerTons3__SSOSessionType (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__SSOSessionType(struct soap*, ns3__SSOSessionType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__SSOSessionType(struct soap*, ns3__SSOSessionType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__SSOSessionType(struct soap*, const char *, int, ns3__SSOSessionType *const*, const char *);
SOAP_FMAC3 ns3__SSOSessionType ** SOAP_FMAC4 soap_get_PointerTons3__SSOSessionType(struct soap*, ns3__SSOSessionType **, const char*, const char*);
SOAP_FMAC3 ns3__SSOSessionType ** SOAP_FMAC4 soap_in_PointerTons3__SSOSessionType(struct soap*, const char*, ns3__SSOSessionType **, const char*);

#ifndef SOAP_TYPE_PointerTons3__SSORoleType
#define SOAP_TYPE_PointerTons3__SSORoleType (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__SSORoleType(struct soap*, ns3__SSORoleType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__SSORoleType(struct soap*, ns3__SSORoleType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__SSORoleType(struct soap*, const char *, int, ns3__SSORoleType *const*, const char *);
SOAP_FMAC3 ns3__SSORoleType ** SOAP_FMAC4 soap_get_PointerTons3__SSORoleType(struct soap*, ns3__SSORoleType **, const char*, const char*);
SOAP_FMAC3 ns3__SSORoleType ** SOAP_FMAC4 soap_in_PointerTons3__SSORoleType(struct soap*, const char*, ns3__SSORoleType **, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE_PointerTons3__SSOUserType
#define SOAP_TYPE_PointerTons3__SSOUserType (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__SSOUserType(struct soap*, ns3__SSOUserType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__SSOUserType(struct soap*, ns3__SSOUserType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__SSOUserType(struct soap*, const char *, int, ns3__SSOUserType *const*, const char *);
SOAP_FMAC3 ns3__SSOUserType ** SOAP_FMAC4 soap_get_PointerTons3__SSOUserType(struct soap*, ns3__SSOUserType **, const char*, const char*);
SOAP_FMAC3 ns3__SSOUserType ** SOAP_FMAC4 soap_in_PointerTons3__SSOUserType(struct soap*, const char*, ns3__SSOUserType **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons3__SSONameValuePairType
#define SOAP_TYPE_std__vectorTemplateOfPointerTons3__SSONameValuePairType (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons3__SSONameValuePairType(struct soap*, std::vector<ns3__SSONameValuePairType * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons3__SSONameValuePairType(struct soap*, const std::vector<ns3__SSONameValuePairType * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons3__SSONameValuePairType(struct soap*, const char*, int, const std::vector<ns3__SSONameValuePairType * >*, const char*);
SOAP_FMAC3 std::vector<ns3__SSONameValuePairType * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons3__SSONameValuePairType(struct soap*, const char*, std::vector<ns3__SSONameValuePairType * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTons3__SSONameValuePairType(soap, n) soap_instantiate_std__vectorTemplateOfPointerTons3__SSONameValuePairType(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTons3__SSONameValuePairType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 std::vector<ns3__SSONameValuePairType * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons3__SSONameValuePairType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons3__SSONameValuePairType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons3__SSORoleType
#define SOAP_TYPE_std__vectorTemplateOfPointerTons3__SSORoleType (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons3__SSORoleType(struct soap*, std::vector<ns3__SSORoleType * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons3__SSORoleType(struct soap*, const std::vector<ns3__SSORoleType * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons3__SSORoleType(struct soap*, const char*, int, const std::vector<ns3__SSORoleType * >*, const char*);
SOAP_FMAC3 std::vector<ns3__SSORoleType * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons3__SSORoleType(struct soap*, const char*, std::vector<ns3__SSORoleType * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTons3__SSORoleType(soap, n) soap_instantiate_std__vectorTemplateOfPointerTons3__SSORoleType(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTons3__SSORoleType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 std::vector<ns3__SSORoleType * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons3__SSORoleType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons3__SSORoleType(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
