/* soapSSOIdentityManagerSOAPBindingProxy.cpp
   Generated by gSOAP 2.7.14 from josso-1.2.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#define _CRTDBG_MAP_ALLOC
#include <iostream>
#include <crtdbg.h>

#include "soapSSOIdentityManagerSOAPBindingProxy.h"

#ifdef _DEBUG
#define DEBUG_NEW new(_NORMAL_BLOCK, __FILE__, __LINE__)
#define new DEBUG_NEW
#endif


SSOIdentityManagerSOAPBindingProxy::SSOIdentityManagerSOAPBindingProxy()
{	SSOIdentityManagerSOAPBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

SSOIdentityManagerSOAPBindingProxy::SSOIdentityManagerSOAPBindingProxy(const struct soap &soap)
{	soap_copy_context(this, &soap);
	SSOIdentityManagerSOAPBindingProxy_init(soap.imode, soap.omode);
}

SSOIdentityManagerSOAPBindingProxy::SSOIdentityManagerSOAPBindingProxy(soap_mode iomode)
{	SSOIdentityManagerSOAPBindingProxy_init(iomode, iomode);
}

SSOIdentityManagerSOAPBindingProxy::SSOIdentityManagerSOAPBindingProxy(soap_mode imode, soap_mode omode)
{	SSOIdentityManagerSOAPBindingProxy_init(imode, omode);
}

void SSOIdentityManagerSOAPBindingProxy::SSOIdentityManagerSOAPBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns4", "urn:org:josso:gateway:ws:1.2:wsdl/SSOIdentityProviderSOAPBinding", NULL, NULL},
	{"ns5", "urn:org:josso:gateway:ws:1.2:wsdl/SSOIdentityManagerSOAPBinding", NULL, NULL},
	{"ns6", "urn:org:josso:gateway:ws:1.2:wsdl/SSOSessionManagerSOAPBinding", NULL, NULL},
	{"ns3", "urn:org:josso:gateway:ws:1.2:protocol", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	if (!this->namespaces)
		this->namespaces = namespaces;
}

SSOIdentityManagerSOAPBindingProxy::~SSOIdentityManagerSOAPBindingProxy()
{ }

void SSOIdentityManagerSOAPBindingProxy::soap_noheader()
{	header = NULL;
}

const SOAP_ENV__Fault *SSOIdentityManagerSOAPBindingProxy::soap_fault()
{	return this->fault;
}

const char *SSOIdentityManagerSOAPBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *SSOIdentityManagerSOAPBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int SSOIdentityManagerSOAPBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

void SSOIdentityManagerSOAPBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void SSOIdentityManagerSOAPBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *SSOIdentityManagerSOAPBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int SSOIdentityManagerSOAPBindingProxy::findUserInSession(ns3__FindUserInSessionRequestType *ns3__FindUserInSessionRequest, ns3__FindUserInSessionResponseType *ns3__FindUserInSessionResponse)
{	struct soap *soap = this;
	struct __ns5__findUserInSession soap_tmp___ns5__findUserInSession;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns5__findUserInSession.ns3__FindUserInSessionRequest = ns3__FindUserInSessionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns5__findUserInSession(soap, &soap_tmp___ns5__findUserInSession);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__findUserInSession(soap, &soap_tmp___ns5__findUserInSession, "-ns5:findUserInSession", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__findUserInSession(soap, &soap_tmp___ns5__findUserInSession, "-ns5:findUserInSession", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__FindUserInSessionResponse)
		return soap_closesock(soap);
	ns3__FindUserInSessionResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FindUserInSessionResponse->soap_get(soap, "ns3:FindUserInSessionResponse", "ns3:FindUserInSessionResponseType");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap, 0);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int SSOIdentityManagerSOAPBindingProxy::findUserInSecurityDomain(ns3__FindUserInSecurityDomainRequestType *ns3__FindUserInSecurityDomainRequest, ns3__FindUserInSecurityDomainResponseType *ns3__FindUserInSecurityDomainResponse)
{	struct soap *soap = this;
	struct __ns5__findUserInSecurityDomain soap_tmp___ns5__findUserInSecurityDomain;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns5__findUserInSecurityDomain.ns3__FindUserInSecurityDomainRequest = ns3__FindUserInSecurityDomainRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns5__findUserInSecurityDomain(soap, &soap_tmp___ns5__findUserInSecurityDomain);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__findUserInSecurityDomain(soap, &soap_tmp___ns5__findUserInSecurityDomain, "-ns5:findUserInSecurityDomain", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__findUserInSecurityDomain(soap, &soap_tmp___ns5__findUserInSecurityDomain, "-ns5:findUserInSecurityDomain", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__FindUserInSecurityDomainResponse)
		return soap_closesock(soap);
	ns3__FindUserInSecurityDomainResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FindUserInSecurityDomainResponse->soap_get(soap, "ns3:FindUserInSecurityDomainResponse", "ns3:FindUserInSecurityDomainResponseType");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap, 0);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int SSOIdentityManagerSOAPBindingProxy::findRolesBySSOSessionId(ns3__FindRolesBySSOSessionIdRequestType *ns3__FindRolesBySSOSessionIdRequest, ns3__FindRolesBySSOSessionIdResponseType *ns3__FindRolesBySSOSessionIdResponse)
{	struct soap *soap = this;
	struct __ns5__findRolesBySSOSessionId soap_tmp___ns5__findRolesBySSOSessionId;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns5__findRolesBySSOSessionId.ns3__FindRolesBySSOSessionIdRequest = ns3__FindRolesBySSOSessionIdRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns5__findRolesBySSOSessionId(soap, &soap_tmp___ns5__findRolesBySSOSessionId);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__findRolesBySSOSessionId(soap, &soap_tmp___ns5__findRolesBySSOSessionId, "-ns5:findRolesBySSOSessionId", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__findRolesBySSOSessionId(soap, &soap_tmp___ns5__findRolesBySSOSessionId, "-ns5:findRolesBySSOSessionId", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__FindRolesBySSOSessionIdResponse)
		return soap_closesock(soap);
	ns3__FindRolesBySSOSessionIdResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FindRolesBySSOSessionIdResponse->soap_get(soap, "ns3:FindRolesBySSOSessionIdResponse", "ns3:FindRolesBySSOSessionIdResponseType");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap, 0);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int SSOIdentityManagerSOAPBindingProxy::userExists(ns3__UserExistsRequestType *ns3__UserExistsRequest, ns3__UserExistsResponseType *ns3__UserExistsResponse)
{	struct soap *soap = this;
	struct __ns5__userExists soap_tmp___ns5__userExists;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns5__userExists.ns3__UserExistsRequest = ns3__UserExistsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns5__userExists(soap, &soap_tmp___ns5__userExists);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__userExists(soap, &soap_tmp___ns5__userExists, "-ns5:userExists", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__userExists(soap, &soap_tmp___ns5__userExists, "-ns5:userExists", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UserExistsResponse)
		return soap_closesock(soap);
	ns3__UserExistsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UserExistsResponse->soap_get(soap, "ns3:UserExistsResponse", "ns3:UserExistsResponseType");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap, 0);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
