/*
 * JOSSO: Java Open Single Sign-On
 *
 * Copyright 2004-2009, Atricore, Inc.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *
 */
package org.josso.seam.console.model;

import org.hibernate.validator.NotNull;

import javax.persistence.*;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "JOSSO_USER_PROPERTY", catalog = "PUBLIC")
public class Property implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
	private Integer id;
	private Username username;
	private String name;
	private String value;

	public Property() {
	}

	public Property(Username username, String name) {
		this.username = username;
		this.name = name;
	}
	public Property(Username username, String name, String value) {
		this.username = username;
		this.name = name;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Login", nullable = false)
	@NotNull
	public Username getUsername() {
		return this.username;
	}

	public void setUsername(Username username) {
		this.username = username;
	}

	@Column(name = "Name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
