/* soapStub.h
   Generated by gSOAP 2.7.14 from josso-1.2.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_ns3__ResolveAuthenticationAssertionRequestType
#define SOAP_TYPE_ns3__ResolveAuthenticationAssertionRequestType (8)
/* ns3:ResolveAuthenticationAssertionRequestType */
struct ns3__ResolveAuthenticationAssertionRequestType
{
	char *requester;	/* required element of type xsd:string */
	char *assertionId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__ResolveAuthenticationAssertionResponseType
#define SOAP_TYPE_ns3__ResolveAuthenticationAssertionResponseType (9)
/* ns3:ResolveAuthenticationAssertionResponseType */
struct ns3__ResolveAuthenticationAssertionResponseType
{
	char *ssoSessionId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
	char *securityDomain;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__AssertIdentityWithSimpleAuthenticationRequestType
#define SOAP_TYPE_ns3__AssertIdentityWithSimpleAuthenticationRequestType (10)
/* ns3:AssertIdentityWithSimpleAuthenticationRequestType */
struct ns3__AssertIdentityWithSimpleAuthenticationRequestType
{
	char *requester;	/* required element of type xsd:string */
	char *securityDomain;	/* required element of type xsd:string */
	char *username;	/* required element of type xsd:string */
	char *password;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__AssertIdentityWithSimpleAuthenticationResponseType
#define SOAP_TYPE_ns3__AssertIdentityWithSimpleAuthenticationResponseType (11)
/* ns3:AssertIdentityWithSimpleAuthenticationResponseType */
struct ns3__AssertIdentityWithSimpleAuthenticationResponseType
{
	char *assertionId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__GlobalSignoffRequestType
#define SOAP_TYPE_ns3__GlobalSignoffRequestType (12)
/* ns3:GlobalSignoffRequestType */
struct ns3__GlobalSignoffRequestType
{
	char *requester;	/* required element of type xsd:string */
	char *ssoSessionId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__GlobalSignoffResponseType
#define SOAP_TYPE_ns3__GlobalSignoffResponseType (13)
/* ns3:GlobalSignoffResponseType */
struct ns3__GlobalSignoffResponseType
{
	char *ssoSessionId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__SSOIdentityProviderErrorType
#define SOAP_TYPE_ns3__SSOIdentityProviderErrorType (14)
/* ns3:SSOIdentityProviderErrorType */
struct ns3__SSOIdentityProviderErrorType
{
	char *errMessage;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__AssertionNotValidErrorType
#define SOAP_TYPE_ns3__AssertionNotValidErrorType (15)
/* ns3:AssertionNotValidErrorType */
struct ns3__AssertionNotValidErrorType
{
	char *assertionId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__FindUserInSessionRequestType
#define SOAP_TYPE_ns3__FindUserInSessionRequestType (16)
/* ns3:FindUserInSessionRequestType */
struct ns3__FindUserInSessionRequestType
{
	char *requester;	/* required element of type xsd:string */
	char *ssoSessionId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__FindUserInSessionResponseType
#define SOAP_TYPE_ns3__FindUserInSessionResponseType (17)
/* ns3:FindUserInSessionResponseType */
struct ns3__FindUserInSessionResponseType
{
	struct ns3__SSOUserType *ns3__SSOUser;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns3:SSOUserType */
};
#endif

#ifndef SOAP_TYPE_ns3__FindUserInSecurityDomainRequestType
#define SOAP_TYPE_ns3__FindUserInSecurityDomainRequestType (20)
/* ns3:FindUserInSecurityDomainRequestType */
struct ns3__FindUserInSecurityDomainRequestType
{
	char *requester;	/* required element of type xsd:string */
	char *securityDomain;	/* required element of type xsd:string */
	char *username;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__FindUserInSecurityDomainResponseType
#define SOAP_TYPE_ns3__FindUserInSecurityDomainResponseType (21)
/* ns3:FindUserInSecurityDomainResponseType */
struct ns3__FindUserInSecurityDomainResponseType
{
	struct ns3__SSOUserType *ns3__SSOUser;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns3:SSOUserType */
};
#endif

#ifndef SOAP_TYPE_ns3__FindRolesBySSOSessionIdRequestType
#define SOAP_TYPE_ns3__FindRolesBySSOSessionIdRequestType (22)
/* ns3:FindRolesBySSOSessionIdRequestType */
struct ns3__FindRolesBySSOSessionIdRequestType
{
	char *requester;	/* required element of type xsd:string */
	char *ssoSessionId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__FindRolesBySSOSessionIdResponseType
#define SOAP_TYPE_ns3__FindRolesBySSOSessionIdResponseType (23)
/* ns3:FindRolesBySSOSessionIdResponseType */
struct ns3__FindRolesBySSOSessionIdResponseType
{
	char *username;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	int __sizeroles;	/* sequence of elements <roles> */
	struct ns3__SSORoleType **roles;	/* optional element of type ns3:SSORoleType */
};
#endif

#ifndef SOAP_TYPE_ns3__UserExistsRequestType
#define SOAP_TYPE_ns3__UserExistsRequestType (27)
/* ns3:UserExistsRequestType */
struct ns3__UserExistsRequestType
{
	char *requester;	/* required element of type xsd:string */
	char *securityDomain;	/* required element of type xsd:string */
	char *username;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__UserExistsResponseType
#define SOAP_TYPE_ns3__UserExistsResponseType (28)
/* ns3:UserExistsResponseType */
struct ns3__UserExistsResponseType
{
	enum xsd__boolean userexists;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns3__SSOIdentityManagerErrorType
#define SOAP_TYPE_ns3__SSOIdentityManagerErrorType (29)
/* ns3:SSOIdentityManagerErrorType */
struct ns3__SSOIdentityManagerErrorType
{
	char *errMessage;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__NoSuchUserErrorType
#define SOAP_TYPE_ns3__NoSuchUserErrorType (30)
/* ns3:NoSuchUserErrorType */
struct ns3__NoSuchUserErrorType
{
	char *securityDomain;	/* required element of type xsd:string */
	char *username;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__InvalidSessionErrorType
#define SOAP_TYPE_ns3__InvalidSessionErrorType (31)
/* ns3:InvalidSessionErrorType */
struct ns3__InvalidSessionErrorType
{
	char *sessionId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__AccessSessionRequestType
#define SOAP_TYPE_ns3__AccessSessionRequestType (32)
/* ns3:AccessSessionRequestType */
struct ns3__AccessSessionRequestType
{
	char *requester;	/* required element of type xsd:string */
	char *ssoSessionId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__AccessSessionResponseType
#define SOAP_TYPE_ns3__AccessSessionResponseType (33)
/* ns3:AccessSessionResponseType */
struct ns3__AccessSessionResponseType
{
	char *ssoSessionId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__SessionRequestType
#define SOAP_TYPE_ns3__SessionRequestType (34)
/* ns3:SessionRequestType */
struct ns3__SessionRequestType
{
	char *requester;	/* required element of type xsd:string */
	char *sessionId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__SessionResponseType
#define SOAP_TYPE_ns3__SessionResponseType (35)
/* ns3:SessionResponseType */
struct ns3__SessionResponseType
{
	struct ns3__SSOSessionType *ns3__SSOSession;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns3:SSOSessionType */
};
#endif

#ifndef SOAP_TYPE_ns3__SSOSessionErrorType
#define SOAP_TYPE_ns3__SSOSessionErrorType (38)
/* ns3:SSOSessionErrorType */
struct ns3__SSOSessionErrorType
{
	char *errMessage;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__NoSuchSessionErrorType
#define SOAP_TYPE_ns3__NoSuchSessionErrorType (39)
/* ns3:NoSuchSessionErrorType */
struct ns3__NoSuchSessionErrorType
{
	char *sessionId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__SSOSessionType
#define SOAP_TYPE_ns3__SSOSessionType (36)
/* ns3:SSOSessionType */
struct ns3__SSOSessionType
{
	char *id;	/* required element of type xsd:string */
	LONG64 creationTime;	/* required element of type xsd:long */
	LONG64 lastAccessTime;	/* required element of type xsd:long */
	int maxInactiveInterval;	/* required element of type xsd:int */
	char *username;	/* required element of type xsd:string */
	LONG64 accessCount;	/* required element of type xsd:long */
	enum xsd__boolean valid;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns3__SSOUserType
#define SOAP_TYPE_ns3__SSOUserType (18)
/* ns3:SSOUserType */
struct ns3__SSOUserType
{
	int __sizeproperties;	/* sequence of elements <properties> */
	struct ns3__SSONameValuePairType **properties;	/* optional element of type ns3:SSONameValuePairType */
	char *name;	/* required element of type xsd:string */
	char *securitydomain;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__SSORoleType
#define SOAP_TYPE_ns3__SSORoleType (24)
/* ns3:SSORoleType */
struct ns3__SSORoleType
{
	char *name;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__SSONameValuePairType
#define SOAP_TYPE_ns3__SSONameValuePairType (41)
/* ns3:SSONameValuePairType */
struct ns3__SSONameValuePairType
{
	char *name;	/* required attribute of type xsd:string */
	char *value;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (44)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	struct ns3__AssertionNotValidErrorType *ns3__AssertionNotValidError;	/* optional element of type ns3:AssertionNotValidErrorType */
	struct ns3__SSOIdentityProviderErrorType *ns3__SSOIdentityProviderError;	/* optional element of type ns3:SSOIdentityProviderErrorType */
	struct ns3__InvalidSessionErrorType *ns3__InvalidSessionError;	/* optional element of type ns3:InvalidSessionErrorType */
	struct ns3__NoSuchUserErrorType *ns3__NoSuchUserError;	/* optional element of type ns3:NoSuchUserErrorType */
	struct ns3__SSOIdentityManagerErrorType *ns3__SSOIdentityManagerError;	/* optional element of type ns3:SSOIdentityManagerErrorType */
	struct ns3__NoSuchSessionErrorType *ns3__NoSuchSessionError;	/* optional element of type ns3:NoSuchSessionErrorType */
	struct ns3__SSOSessionErrorType *ns3__SSOSessionError;	/* optional element of type ns3:SSOSessionErrorType */
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE___ns4__resolveAuthenticationAssertion
#define SOAP_TYPE___ns4__resolveAuthenticationAssertion (57)
/* Operation wrapper: */
struct __ns4__resolveAuthenticationAssertion
{
	struct ns3__ResolveAuthenticationAssertionRequestType *ns3__ResolveAuthenticationAssertionRequest;	/* optional element of type ns3:ResolveAuthenticationAssertionRequestType */
};
#endif

#ifndef SOAP_TYPE___ns4__assertIdentityWithSimpleAuthentication
#define SOAP_TYPE___ns4__assertIdentityWithSimpleAuthentication (61)
/* Operation wrapper: */
struct __ns4__assertIdentityWithSimpleAuthentication
{
	struct ns3__AssertIdentityWithSimpleAuthenticationRequestType *ns3__AssertIdentityWithSimpleAuthenticationRequest;	/* optional element of type ns3:AssertIdentityWithSimpleAuthenticationRequestType */
};
#endif

#ifndef SOAP_TYPE___ns4__globalSignoff
#define SOAP_TYPE___ns4__globalSignoff (65)
/* Operation wrapper: */
struct __ns4__globalSignoff
{
	struct ns3__GlobalSignoffRequestType *ns3__GlobalSignoffRequest;	/* optional element of type ns3:GlobalSignoffRequestType */
};
#endif

#ifndef SOAP_TYPE___ns5__findUserInSession
#define SOAP_TYPE___ns5__findUserInSession (69)
/* Operation wrapper: */
struct __ns5__findUserInSession
{
	struct ns3__FindUserInSessionRequestType *ns3__FindUserInSessionRequest;	/* optional element of type ns3:FindUserInSessionRequestType */
};
#endif

#ifndef SOAP_TYPE___ns5__findUserInSecurityDomain
#define SOAP_TYPE___ns5__findUserInSecurityDomain (73)
/* Operation wrapper: */
struct __ns5__findUserInSecurityDomain
{
	struct ns3__FindUserInSecurityDomainRequestType *ns3__FindUserInSecurityDomainRequest;	/* optional element of type ns3:FindUserInSecurityDomainRequestType */
};
#endif

#ifndef SOAP_TYPE___ns5__findRolesBySSOSessionId
#define SOAP_TYPE___ns5__findRolesBySSOSessionId (77)
/* Operation wrapper: */
struct __ns5__findRolesBySSOSessionId
{
	struct ns3__FindRolesBySSOSessionIdRequestType *ns3__FindRolesBySSOSessionIdRequest;	/* optional element of type ns3:FindRolesBySSOSessionIdRequestType */
};
#endif

#ifndef SOAP_TYPE___ns5__userExists
#define SOAP_TYPE___ns5__userExists (81)
/* Operation wrapper: */
struct __ns5__userExists
{
	struct ns3__UserExistsRequestType *ns3__UserExistsRequest;	/* optional element of type ns3:UserExistsRequestType */
};
#endif

#ifndef SOAP_TYPE___ns6__accessSession
#define SOAP_TYPE___ns6__accessSession (85)
/* Operation wrapper: */
struct __ns6__accessSession
{
	struct ns3__AccessSessionRequestType *ns3__AccessSessionRequest;	/* optional element of type ns3:AccessSessionRequestType */
};
#endif

#ifndef SOAP_TYPE___ns6__getSession
#define SOAP_TYPE___ns6__getSession (89)
/* Operation wrapper: */
struct __ns6__getSession
{
	struct ns3__SessionRequestType *ns3__SessionRequest;	/* optional element of type ns3:SessionRequestType */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (90)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (91)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (93)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (94)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__resolveAuthenticationAssertion(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__ResolveAuthenticationAssertionRequestType *ns3__ResolveAuthenticationAssertionRequest, struct ns3__ResolveAuthenticationAssertionResponseType *ns3__ResolveAuthenticationAssertionResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__assertIdentityWithSimpleAuthentication(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__AssertIdentityWithSimpleAuthenticationRequestType *ns3__AssertIdentityWithSimpleAuthenticationRequest, struct ns3__AssertIdentityWithSimpleAuthenticationResponseType *ns3__AssertIdentityWithSimpleAuthenticationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__globalSignoff(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__GlobalSignoffRequestType *ns3__GlobalSignoffRequest, struct ns3__GlobalSignoffResponseType *ns3__GlobalSignoffResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns5__findUserInSession(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__FindUserInSessionRequestType *ns3__FindUserInSessionRequest, struct ns3__FindUserInSessionResponseType *ns3__FindUserInSessionResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns5__findUserInSecurityDomain(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__FindUserInSecurityDomainRequestType *ns3__FindUserInSecurityDomainRequest, struct ns3__FindUserInSecurityDomainResponseType *ns3__FindUserInSecurityDomainResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns5__findRolesBySSOSessionId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__FindRolesBySSOSessionIdRequestType *ns3__FindRolesBySSOSessionIdRequest, struct ns3__FindRolesBySSOSessionIdResponseType *ns3__FindRolesBySSOSessionIdResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns5__userExists(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__UserExistsRequestType *ns3__UserExistsRequest, struct ns3__UserExistsResponseType *ns3__UserExistsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns6__accessSession(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__AccessSessionRequestType *ns3__AccessSessionRequest, struct ns3__AccessSessionResponseType *ns3__AccessSessionResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns6__getSession(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__SessionRequestType *ns3__SessionRequest, struct ns3__SessionResponseType *ns3__SessionResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
