/* soapClient.c
   Generated by gSOAP 2.7.16 from josso-1.2.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.16 2010-12-02 16:18:49 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__resolveAuthenticationAssertion(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__ResolveAuthenticationAssertionRequestType *ns3__ResolveAuthenticationAssertionRequest, struct ns3__ResolveAuthenticationAssertionResponseType *ns3__ResolveAuthenticationAssertionResponse)
{	struct __ns4__resolveAuthenticationAssertion soap_tmp___ns4__resolveAuthenticationAssertion;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns4__resolveAuthenticationAssertion.ns3__ResolveAuthenticationAssertionRequest = ns3__ResolveAuthenticationAssertionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns4__resolveAuthenticationAssertion(soap, &soap_tmp___ns4__resolveAuthenticationAssertion);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__resolveAuthenticationAssertion(soap, &soap_tmp___ns4__resolveAuthenticationAssertion, "-ns4:resolveAuthenticationAssertion", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__resolveAuthenticationAssertion(soap, &soap_tmp___ns4__resolveAuthenticationAssertion, "-ns4:resolveAuthenticationAssertion", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__ResolveAuthenticationAssertionResponse)
		return soap_closesock(soap);
	soap_default_ns3__ResolveAuthenticationAssertionResponseType(soap, ns3__ResolveAuthenticationAssertionResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__ResolveAuthenticationAssertionResponseType(soap, ns3__ResolveAuthenticationAssertionResponse, "ns3:ResolveAuthenticationAssertionResponse", "ns3:ResolveAuthenticationAssertionResponseType");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__assertIdentityWithSimpleAuthentication(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__AssertIdentityWithSimpleAuthenticationRequestType *ns3__AssertIdentityWithSimpleAuthenticationRequest, struct ns3__AssertIdentityWithSimpleAuthenticationResponseType *ns3__AssertIdentityWithSimpleAuthenticationResponse)
{	struct __ns4__assertIdentityWithSimpleAuthentication soap_tmp___ns4__assertIdentityWithSimpleAuthentication;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns4__assertIdentityWithSimpleAuthentication.ns3__AssertIdentityWithSimpleAuthenticationRequest = ns3__AssertIdentityWithSimpleAuthenticationRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns4__assertIdentityWithSimpleAuthentication(soap, &soap_tmp___ns4__assertIdentityWithSimpleAuthentication);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__assertIdentityWithSimpleAuthentication(soap, &soap_tmp___ns4__assertIdentityWithSimpleAuthentication, "-ns4:assertIdentityWithSimpleAuthentication", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__assertIdentityWithSimpleAuthentication(soap, &soap_tmp___ns4__assertIdentityWithSimpleAuthentication, "-ns4:assertIdentityWithSimpleAuthentication", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__AssertIdentityWithSimpleAuthenticationResponse)
		return soap_closesock(soap);
	soap_default_ns3__AssertIdentityWithSimpleAuthenticationResponseType(soap, ns3__AssertIdentityWithSimpleAuthenticationResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__AssertIdentityWithSimpleAuthenticationResponseType(soap, ns3__AssertIdentityWithSimpleAuthenticationResponse, "ns3:AssertIdentityWithSimpleAuthenticationResponse", "ns3:AssertIdentityWithSimpleAuthenticationResponseType");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__globalSignoff(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__GlobalSignoffRequestType *ns3__GlobalSignoffRequest, struct ns3__GlobalSignoffResponseType *ns3__GlobalSignoffResponse)
{	struct __ns4__globalSignoff soap_tmp___ns4__globalSignoff;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns4__globalSignoff.ns3__GlobalSignoffRequest = ns3__GlobalSignoffRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns4__globalSignoff(soap, &soap_tmp___ns4__globalSignoff);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__globalSignoff(soap, &soap_tmp___ns4__globalSignoff, "-ns4:globalSignoff", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__globalSignoff(soap, &soap_tmp___ns4__globalSignoff, "-ns4:globalSignoff", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GlobalSignoffResponse)
		return soap_closesock(soap);
	soap_default_ns3__GlobalSignoffResponseType(soap, ns3__GlobalSignoffResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__GlobalSignoffResponseType(soap, ns3__GlobalSignoffResponse, "ns3:GlobalSignoffResponse", "ns3:GlobalSignoffResponseType");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns5__findUserInSession(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__FindUserInSessionRequestType *ns3__FindUserInSessionRequest, struct ns3__FindUserInSessionResponseType *ns3__FindUserInSessionResponse)
{	struct __ns5__findUserInSession soap_tmp___ns5__findUserInSession;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns5__findUserInSession.ns3__FindUserInSessionRequest = ns3__FindUserInSessionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns5__findUserInSession(soap, &soap_tmp___ns5__findUserInSession);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__findUserInSession(soap, &soap_tmp___ns5__findUserInSession, "-ns5:findUserInSession", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__findUserInSession(soap, &soap_tmp___ns5__findUserInSession, "-ns5:findUserInSession", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__FindUserInSessionResponse)
		return soap_closesock(soap);
	soap_default_ns3__FindUserInSessionResponseType(soap, ns3__FindUserInSessionResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__FindUserInSessionResponseType(soap, ns3__FindUserInSessionResponse, "ns3:FindUserInSessionResponse", "ns3:FindUserInSessionResponseType");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns5__findUserInSecurityDomain(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__FindUserInSecurityDomainRequestType *ns3__FindUserInSecurityDomainRequest, struct ns3__FindUserInSecurityDomainResponseType *ns3__FindUserInSecurityDomainResponse)
{	struct __ns5__findUserInSecurityDomain soap_tmp___ns5__findUserInSecurityDomain;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns5__findUserInSecurityDomain.ns3__FindUserInSecurityDomainRequest = ns3__FindUserInSecurityDomainRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns5__findUserInSecurityDomain(soap, &soap_tmp___ns5__findUserInSecurityDomain);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__findUserInSecurityDomain(soap, &soap_tmp___ns5__findUserInSecurityDomain, "-ns5:findUserInSecurityDomain", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__findUserInSecurityDomain(soap, &soap_tmp___ns5__findUserInSecurityDomain, "-ns5:findUserInSecurityDomain", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__FindUserInSecurityDomainResponse)
		return soap_closesock(soap);
	soap_default_ns3__FindUserInSecurityDomainResponseType(soap, ns3__FindUserInSecurityDomainResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__FindUserInSecurityDomainResponseType(soap, ns3__FindUserInSecurityDomainResponse, "ns3:FindUserInSecurityDomainResponse", "ns3:FindUserInSecurityDomainResponseType");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns5__findRolesBySSOSessionId(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__FindRolesBySSOSessionIdRequestType *ns3__FindRolesBySSOSessionIdRequest, struct ns3__FindRolesBySSOSessionIdResponseType *ns3__FindRolesBySSOSessionIdResponse)
{	struct __ns5__findRolesBySSOSessionId soap_tmp___ns5__findRolesBySSOSessionId;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns5__findRolesBySSOSessionId.ns3__FindRolesBySSOSessionIdRequest = ns3__FindRolesBySSOSessionIdRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns5__findRolesBySSOSessionId(soap, &soap_tmp___ns5__findRolesBySSOSessionId);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__findRolesBySSOSessionId(soap, &soap_tmp___ns5__findRolesBySSOSessionId, "-ns5:findRolesBySSOSessionId", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__findRolesBySSOSessionId(soap, &soap_tmp___ns5__findRolesBySSOSessionId, "-ns5:findRolesBySSOSessionId", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__FindRolesBySSOSessionIdResponse)
		return soap_closesock(soap);
	soap_default_ns3__FindRolesBySSOSessionIdResponseType(soap, ns3__FindRolesBySSOSessionIdResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__FindRolesBySSOSessionIdResponseType(soap, ns3__FindRolesBySSOSessionIdResponse, "ns3:FindRolesBySSOSessionIdResponse", "ns3:FindRolesBySSOSessionIdResponseType");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns5__userExists(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__UserExistsRequestType *ns3__UserExistsRequest, struct ns3__UserExistsResponseType *ns3__UserExistsResponse)
{	struct __ns5__userExists soap_tmp___ns5__userExists;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns5__userExists.ns3__UserExistsRequest = ns3__UserExistsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns5__userExists(soap, &soap_tmp___ns5__userExists);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns5__userExists(soap, &soap_tmp___ns5__userExists, "-ns5:userExists", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns5__userExists(soap, &soap_tmp___ns5__userExists, "-ns5:userExists", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UserExistsResponse)
		return soap_closesock(soap);
	soap_default_ns3__UserExistsResponseType(soap, ns3__UserExistsResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__UserExistsResponseType(soap, ns3__UserExistsResponse, "ns3:UserExistsResponse", "ns3:UserExistsResponseType");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns6__accessSession(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__AccessSessionRequestType *ns3__AccessSessionRequest, struct ns3__AccessSessionResponseType *ns3__AccessSessionResponse)
{	struct __ns6__accessSession soap_tmp___ns6__accessSession;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__accessSession.ns3__AccessSessionRequest = ns3__AccessSessionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__accessSession(soap, &soap_tmp___ns6__accessSession);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__accessSession(soap, &soap_tmp___ns6__accessSession, "-ns6:accessSession", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__accessSession(soap, &soap_tmp___ns6__accessSession, "-ns6:accessSession", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__AccessSessionResponse)
		return soap_closesock(soap);
	soap_default_ns3__AccessSessionResponseType(soap, ns3__AccessSessionResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__AccessSessionResponseType(soap, ns3__AccessSessionResponse, "ns3:AccessSessionResponse", "ns3:AccessSessionResponseType");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns6__getSession(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__SessionRequestType *ns3__SessionRequest, struct ns3__SessionResponseType *ns3__SessionResponse)
{	struct __ns6__getSession soap_tmp___ns6__getSession;
	if (!soap_endpoint)
		soap_endpoint = "http://replace";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__getSession.ns3__SessionRequest = ns3__SessionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__getSession(soap, &soap_tmp___ns6__getSession);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__getSession(soap, &soap_tmp___ns6__getSession, "-ns6:getSession", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__getSession(soap, &soap_tmp___ns6__getSession, "-ns6:getSession", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__SessionResponse)
		return soap_closesock(soap);
	soap_default_ns3__SessionResponseType(soap, ns3__SessionResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__SessionResponseType(soap, ns3__SessionResponse, "ns3:SessionResponse", "ns3:SessionResponseType");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
